import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import React from "react";
import { ShipCard } from "../components/ShipCard";
import { useFleet } from "../hooks/useFleet";

const Home: NextPage = () => {
  const { fleets } = useFleet();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {/*{ships.map((ship) => (*/}
        {/*  <div key={ship.id}>{ship.names.en}</div>*/}
        {/*))}*/}
        {/*<div style={{ marginBottom: 20 }}>{selectedShip?.label}</div>*/}
        {/*{Object.entries<Ship>(ship.stats.baseStats).map(([key, value]) => (*/}
        {/*  <div key={key}>*/}
        {/*    {key}: {value}*/}
        {/*  </div>*/}
        {/*))}*/}
        {/*{Object.entries<Ship>(ship.stats.level100).map(([key, value]) => (*/}
        {/*  <div key={key}>*/}
        {/*    {key}: {value}*/}
        {/*  </div>*/}
        {/*))}*/}

        <div style={{ display: "grid", gridTemplateColumns: "repeat(3, 1fr)" }}>
          <ShipCard />
          <ShipCard />
          <ShipCard />

          <ShipCard />
          <ShipCard />
          <ShipCard />
        </div>
      </main>
    </div>
  );
};

export default Home;
