import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Slider from "@mui/material/Slider";
import { useState } from "react";
import shipsJson from "../data/ship_data_statistics.json";
import enhancementsJson from "../data/ship_data_strengthen.json";
import {
  Autocomplete,
  FormControlLabel,
  Switch,
  TextField,
  ToggleButton,
  ToggleButtonGroup,
} from "@mui/material";
import { Affection, Attrs, Enhancements, Ship, Stat } from "../types/ship";
import {
  affinity,
  attributePosition,
  attributes,
  nationality,
} from "../styles/utils/constants";

const ships = Object.fromEntries(
  Object.entries(shipsJson as Ship[]).filter(
    ([, ship]) => ship.is_character === 1
  )
);

const enhancements = enhancementsJson as unknown as Enhancements;

const getGroupId = (id: number) => id.toString().slice(0, -1);

const getShipById = (id: number) => {
  const groupId = getGroupId(id);

  return Object.entries(ships)
    .filter(([, ship]) => ship.id.toString().startsWith(groupId))
    .map(([, s]) => s);
};

const getName = (ship: Ship) => {
  return `${ship.name} (${nationality[ship.nationality]})`;
};

const Home: NextPage = () => {
  const [level, setLevel] = useState<number>(30);
  const [selectedShip, setSelectedShip] = useState<{
    label: string;
    id: number;
  } | null>(null);
  const [affection, setAffection] = useState<Affection>("stranger");
  const [maxEnhancements, setMaxEnhancements] = useState<boolean>(true);

  const handleChange = (event: Event, newValue: number | number[]) => {
    setLevel(newValue as number);
  };

  const ship = selectedShip
    ? getShipById(selectedShip.id)[
        level <= 70
          ? 0
          : level > 70 && level <= 80
          ? 1
          : level > 80 && level <= 90
          ? 2
          : 3
      ]
    : undefined;

  const getStat = (
    attrs: Attrs,
    growth: Attrs,
    stat: Stat,
    level: number,
    enhance: number = 0,
    affinity: number = 1
  ) => {
    return (
      (attrs[attributes[stat][1]] +
        ((level - 1) * growth[attributes[stat][1]]) / 1000 +
        enhance) *
      affinity
    );
  };
  const options = Object.entries(ships)
    .filter(([id]) => id.endsWith("1"))
    .map(([, s]) => ({
      label: getName(s),
      id: s.id,
    }))
    .sort();

  const stats = ship
    ? Object.fromEntries(
        Object.entries(attributes).map(([key, values]) => [
          key,
          Math.floor(
            getStat(
              ship.attrs,
              ship.attrs_growth,
              key as Stat,
              level,
              values[3] !== undefined
                ? maxEnhancements && selectedShip
                  ? enhancements[getGroupId(selectedShip.id)].durability[
                      attributePosition[values[3]]
                    ]
                  : 0
                : 0,
              affinity[affection]
            )
          ),
        ])
      )
    : undefined;

  const gunReloadTime =
    stats && (3880 / 150) * Math.sqrt(200 / (stats.reload * (1 + 0) + 100));

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {/*{ships.map((ship) => (*/}
        {/*  <div key={ship.id}>{ship.names.en}</div>*/}
        {/*))}*/}
        <div style={{ marginBottom: 20 }}>{selectedShip?.label}</div>
        {/*{Object.entries<Ship>(ship.stats.baseStats).map(([key, value]) => (*/}
        {/*  <div key={key}>*/}
        {/*    {key}: {value}*/}
        {/*  </div>*/}
        {/*))}*/}
        {/*{Object.entries<Ship>(ship.stats.level100).map(([key, value]) => (*/}
        {/*  <div key={key}>*/}
        {/*    {key}: {value}*/}
        {/*  </div>*/}
        {/*))}*/}
        <div style={{ display: "flex" }}>
          <div style={{ display: "grid" }}>
            <div style={{ width: 200 }}>
              <Autocomplete
                renderInput={(params) => (
                  <TextField {...params} label="Ship" fullWidth />
                )}
                options={options}
                onChange={(event, newValue) => {
                  setSelectedShip(newValue);
                }}
                value={selectedShip}
                // getOptionLabel={(option) => option.label}
              />
            </div>

            <FormControlLabel
              control={
                <Switch
                  checked={maxEnhancements}
                  onChange={(event, checked) => setMaxEnhancements(checked)}
                />
              }
              label="Max enhancements"
            />

            <ToggleButtonGroup
              value={affection}
              exclusive
              onChange={(
                event: React.MouseEvent<HTMLElement>,
                newAffection: Affection | null
              ) => {
                if (!newAffection) {
                  return;
                }

                setAffection(newAffection);
              }}
            >
              {Object.keys(affinity).map((val) => (
                <ToggleButton value={val} key={val}>
                  {val}
                </ToggleButton>
              ))}
            </ToggleButtonGroup>
          </div>

          {ship && stats && (
            <div>
              {Object.entries(stats).map(([stat, value]) => (
                <div key={stat}>
                  {stat}: {value}
                </div>
              ))}
            </div>
          )}
        </div>

        <Slider
          min={1}
          max={125}
          value={level}
          onChange={handleChange}
          valueLabelDisplay="auto"
        />

        {gunReloadTime?.toFixed(2)}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
