import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import React, { useState } from "react";
import { Autocomplete, TextField } from "@mui/material";
import { ShipData } from "../types/ship";
import { nationality } from "../styles/utils/constants";
import { ships } from "../styles/utils/data";
import { Ship } from "../components/Ship";

const getName = (ship: ShipData) => {
  return `${ship.name} (${nationality[ship.nationality]})`;
};

const options = Object.entries(ships)
  .filter(([id]) => id.endsWith("1"))
  .map(([, s]) => ({
    label: getName(s),
    id: s.id,
  }))
  .sort();

const Home: NextPage = () => {
  const [selectedShip, setSelectedShip] = useState<{
    label: string;
    id: number;
  } | null>(null);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {/*{ships.map((ship) => (*/}
        {/*  <div key={ship.id}>{ship.names.en}</div>*/}
        {/*))}*/}
        {/*<div style={{ marginBottom: 20 }}>{selectedShip?.label}</div>*/}
        {/*{Object.entries<Ship>(ship.stats.baseStats).map(([key, value]) => (*/}
        {/*  <div key={key}>*/}
        {/*    {key}: {value}*/}
        {/*  </div>*/}
        {/*))}*/}
        {/*{Object.entries<Ship>(ship.stats.level100).map(([key, value]) => (*/}
        {/*  <div key={key}>*/}
        {/*    {key}: {value}*/}
        {/*  </div>*/}
        {/*))}*/}

        <div style={{ width: 200 }}>
          <Autocomplete
            renderInput={(params) => (
              <TextField {...params} label="Ship" fullWidth />
            )}
            options={options}
            onChange={(event, newValue) => {
              setSelectedShip(newValue);
            }}
            value={selectedShip}
            // getOptionLabel={(option) => option.label}
          />
        </div>

        {selectedShip?.id && <Ship id={selectedShip.id} />}
      </main>
    </div>
  );
};

export default Home;
